# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - 2.13.14
          - 2.12.19
          - 3.3.3

    steps:
    - uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: build ${{ matrix.scala }}
      run: sbt ++${{ matrix.scala }} clean coverage test
    - name: test coverage
      if: success()
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: Scala ${{ matrix.scala }}
      run: sbt ++${{ matrix.scala }} coverageReport coverageAggregate coveralls
